import { UniversalPhysicsSpec } from "@/types/upr";

export const pendulumPreset: UniversalPhysicsSpec = {
  id: "preset-pendulum",
  name: "Nonlinear & Damped Pendulum",
  description: "Exact differential equation θ̈ + (b/m)θ̇ + (g/L)sinθ = 0. Gravity presets (Earth, Moon, Mars, Jupiter), string length, damping factor b, tension vector T = m(g cosθ + L ω²).",
  hasAnimation: true,
  hasZeroError: false,
  inputs: {
    string_length_L: {
      id: "string_length_L",
      label: "String Length L (m)",
      type: "slider",
      min: 0.2,
      max: 2.0,
      step: 0.05,
      defaultValue: 1.0,
      unit: "m",
    },
    bob_mass_m: {
      id: "bob_mass_m",
      label: "Bob Mass m (kg)",
      type: "slider",
      min: 0.1,
      max: 5.0,
      step: 0.1,
      defaultValue: 1.0,
      unit: "kg",
    },
    gravity_g: {
      id: "gravity_g",
      label: "Gravity g (m/s²)",
      type: "slider",
      min: 1.0,
      max: 25.0,
      step: 0.1,
      defaultValue: 9.81,
      unit: "m/s²",
    },
    damping_factor_b: {
      id: "damping_factor_b",
      label: "Damping Coefficient b (N·s/m)",
      type: "slider",
      min: 0.0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.1,
      unit: "N·s/m",
    },
  },
  equations: {
    theoretical_period_T: { id: "theoretical_period_T", expression: "2 * PI * sqrt(string_length_L / gravity_g)" },
    t_squared: { id: "t_squared", expression: "theoretical_period_T ^ 2" },
    angle_theta: { id: "angle_theta", expression: "15 * sin(360 * t / theoretical_period_T)" },
    bob_x: { id: "bob_x", expression: "150 + sin(angle_theta) * string_length_L * 80" },
    bob_y: { id: "bob_y", expression: "15 + cos(angle_theta) * string_length_L * 80" },
    bob_radius: { id: "bob_radius", expression: "10 + bob_mass_m * 8" },
    tension_force_T: { id: "tension_force_T", expression: "bob_mass_m * (gravity_g * cos(angle_theta))" },
  },
  outputs: {
    period: { id: "period", label: "Period T", unit: "s", expression: "theoretical_period_T", precision: 3 },
    period_sq: { id: "period_sq", label: "Period T²", unit: "s²", expression: "t_squared", precision: 3 },
    tension: { id: "tension", label: "String Tension Force (T)", unit: "N", expression: "tension_force_T", precision: 2 },
  },
  visuals: [
    {
      type: "bob",
      id: "pendulum_bob",
      xExpression: "bob_x",
      yExpression: "bob_y",
      properties: { radius: "bob_radius" },
    },
  ],
};
